trigger:
  batch: true
  branches:
    include:
    - '*'

stages:
- stage: onPush
  jobs:
  - job: onPushJob
    pool:
      vmImage: 'Ubuntu 20.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.9'
      inputs:
        versionSpec: 3.9

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
        python -m pip install --upgrade pip
        pip install databricks_cli
      displayName: 'Install dependencies'

    - script: |
        python deploy/deploy_v2.py  --branch_name $(Build.SourceBranchName)
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Run integration test on Databricks'

